name: github-pages

on:
  push:
    branches: ["main"]

  schedule:
    - cron: "*/10 * * * *"

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.19.0"

      - name: run auto-disclosure
        env:
          SECRET_KEY: ${{secrets.SECRET_KEY}}
          EVENT_NAME: ${{github.event_name}}
        run: go run lastwill.go -disclose

      - name: setup pages
        uses: actions/configure-pages@v2

      - name: upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "."

      - name: deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
